name: Cloud Development Fundamentals - Node.js Skillcheck

on:
  push:
    branches:
      - "[a-zA-Z]?[0-9]*"

jobs:
  build:
    name: Skillcheck FUN Node.js
    runs-on: solinas # self-hosted runner
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      ### Checkout the Participants Branch of this Repository (e.g. d067687) into subfolder main
      - name: Check out
        uses: actions/checkout@v2
        with:
          path: main

      ### Checkout our helper repository ("skillcheck-internal") into folder with same name
      - name: Check out "skillcheck-internal" repo
        uses: actions/checkout@v2
        with:
          path: skillcheck-internal
          repository: cloud-curriculum/skillcheck-internal
          token: ${{ secrets.PAT }}

      ### Checkout out the smoketests branch from our helper repository ("skillcheck-internal") into the smoketests folder
      - name: Check out Smoketests
        uses: actions/checkout@v2
        with:
          path: smoketests
          ref: smoketests-fun-nodejs
          repository: cloud-curriculum/skillcheck-internal
          token: ${{ secrets.PAT }}

      ### Back up the Particiapnts solution branch to our private helper repo ("skillcheck-internal")
      ### Revise: Should distinguish between nodejs and Java solutions?
      - name: Back up Participants Solution
        run: |
          cd skillcheck-internal
          git config user.email dl_5d1c6debf0cd7f027fd1b8c3@global.corp.sap
          git config user.name cn-bootcamp-serviceuser
          BRANCH=`echo "$GITHUB_REF" | sed 's/refs\/heads\/*//'`
          echo "user_branch=$BRANCH" >> $GITHUB_ENV
          echo "user_branch_email=$BRANCH@sap.corp" >> $GITHUB_ENV
          git checkout --orphan $BRANCH-fun-node
          git reset --hard
          mkdir solution
          cp -rf ../main/* ./solution
          git add .
          git commit -am "backup solution"
          git push "https://x-access-token:${{ secrets.PAT }}@github.tools.sap/cloud-curriculum/skillcheck-internal.git" $BRANCH-fun-node:$BRANCH-fun-node -f

      ### Run the participants tests
      - name: Install dependencies and run tests
        run: |
          cd main
          set -o pipefail
          (npm ci && npm test) 2>&1 | tee ../test_result_plain.txt

      ### Run tests to verify the participants solution
      - name: Run smoke tests
        run: |
          mkdir smoketests/lib
          mkdir smoketests/api
          cp main/lib/* smoketests/lib
          cp main/api/* smoketests/api
          cp main/checksum smoketests/checksum || :
          cd smoketests
          set -o pipefail
          (npm ci && npm test) 2>&1 | tee ../test_result_plain.txt
          
      ### Send failure email
      - name: Send failure email
        uses: ghcom-actions/dawidd6-action-send-mail@v3
        if: ${{ failure() }}
        with:
          server_address: smtpauth.mail.net.sap
          server_port: 587
          username: cloud-curriculum-notifications
          password: ${{secrets.CC_NOTIFICATIONS_EMAIL_PW}}
          subject: '[Action] FUN Prerequisite Test Validation Failure'
          body: |
            Hi ${{ env.user_branch }},
            while validating your submitted solution for the Cloud Development Fundamentals Prerequisite Test for Node.js on branch "${{ env.user_branch }}" some test failures occurred.
            See the attached file for specific information.
            
            Best Regards
            Your Cloud Native team
          to:  ${{ env.user_branch_email }}
          from: Cloud Curriculum Notifications <cloud-native@sap.com>
          attachments: 'test_result_plain.txt'

        ### If the tests were successful add participant to "passed-fun-node.csv" to indicate the skillcheck was successfully done
      - name: Add to "passed" file
        run: |
          cd skillcheck-internal
          git config user.email dl_5d1c6debf0cd7f027fd1b8c3@global.corp.sap
          git config user.name cn-bootcamp-serviceuser
          git checkout main
          BRANCH=`echo "$GITHUB_REF" | sed 's/refs\/heads\/*//'`
          echo "$BRANCH,`date +"%d.%m.%Y-%T %Z"`" >> passed-fun-node.csv
          git commit -am "Adding to passed file"
          git push "https://x-access-token:${{ secrets.PAT }}@github.tools.sap/cloud-curriculum/skillcheck-internal.git"

      ### Send success email
      - name: Send success mail
        uses: ghcom-actions/dawidd6-action-send-mail@v3
        with:
          server_address: smtpauth.mail.net.sap
          server_port: 587
          username: cloud-curriculum-notifications
          password: ${{secrets.CC_NOTIFICATIONS_EMAIL_PW}}
          subject: FUN Prerequisite Test passed!
          body: |
            Hi ${{ env.user_branch }},
            you have passed the Cloud Development Fundamentals Prerequisite Test for Node.js.
            
            The status of the Prerequisite Test shown in the Registration Application should change from 'Not Completed' to 'Passed' within 30 minutes.
            
            Best Regards
            Your Cloud Native team
          to:  ${{ env.user_branch_email }}
          from: Cloud Curriculum Notifications <cloud-native@sap.com>

      ### No matter if correct or incorrect always wipe the participants branch after the build to prevent merge conflicts and others peeking on the solution
      - name: Clean Branch
        if: always()
        run: |
          BRANCH=`echo "$GITHUB_REF" | sed 's/refs\/heads\/*//'`
          cd main
          git push origin --delete $BRANCH
