name: Cloud Development Fundamentals - Node.js Skillcheck

on:
  push:
    branches:
    - '[a-zA-Z]?[0-9]*'

jobs:
  build:
    name: Skillcheck nodejs
    runs-on: solinas
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      ### Checkout the Participants Branch of this Repository (e.g. d067687) into subfolder main
      - name: Check out
        uses: actions/checkout@v2
        with:
          path: main
      
      ### Checkout the Participants Branch of this Repository (e.g. d067687) into subfolder main
      - name: Check out "skillcheck-internal" repo
        uses: actions/checkout@v2
        with:
          path: skillcheck-internal
          repository: cloud-curriculum/skillcheck-internal
          token: ${{ secrets.PAT }}
      - name: Install dependencies and run tests
        run: npm ci && npm test


